#groups: get all -> 200
GET  http://localhost:8080/
Content-Type: application/json

> {%
  client.test("success", function() {
    client.assert(response.status === 200, "Response status is 200");
  });

  client.test("response", function() {
    client.assert(Array.isArray(response.body));
    client.assert(response.body.length === 2);
  });

  client.test("response content-type is json", function() {
    var type = response.contentType.mimeType;
    client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
  });
%}

###
#groups: get instances by group-> 200
GET  http://localhost:8080/particle-detector-2
Content-Type: application/json

> {%
  client.test("success", function() {
    client.assert(response.status === 200, "Response status is 200");
  });

  client.test("response array", function() {
    client.assert(Array.isArray(response.body));
    client.assert(response.body.length === 1);
  });

  client.test("response object", function() {
    client.assert(response.body[0].group === 'particle-detector-2');
  });

  client.test("response content-type is json", function() {
    var type = response.contentType.mimeType;
    client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
  });
%}

###
#intances: registred new instance -> 201
POST  http://localhost:8080/particle-detector-4/126
Content-Type: application/json

> {%
  client.test("success", function() {
    client.assert(response.status === 201, "Response status is 201");
  });

  client.test("response object", function() {
    client.assert(response.body['id'] === "126");
    // client.assert(response.body['group'] === 'particle-detector-4');
  });

  client.test("response content-type is json", function() {
    var type = response.contentType.mimeType;
    client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
  });
%}

###
#intances: unregistred existing instance -> 201
DELETE  http://localhost:8080/particle-detector-4/126
Content-Type: application/json

> {%
  client.test("success", function() {
    client.assert(response.status === 200, "Response status is 200");
  });
%}
